general:
steps:
  mtaBuild:
    buildTarget: 'CF'
cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    org: 'i530140trial'
    space: 'dev'
    credentialsId: 'CF_CREDENTIALSID'
