general:
steps:
  mtaBuild:
    buildTarget: 'CF'
cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'https://api.cf.eu10.hana.ondemand.com'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
