general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'i530140trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
  newmanExecute:
      newmanCollection: 'C:\Development\PostmanCollections\CompanyManager.postman_collection.json'
